.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "SAMBAMBA\-MILEUP" "1" "December 2014" "" ""
.
.SH "NAME"
\fBsambamba\-mileup\fR \- make a pileup
.
.SH "SYNOPSIS"
\fBsambamba mpileup\fR \fIOPTIONS\fR <input1\.bam> <input2\.bam> [\.\.\.] [\-\-samtools \fIsamtools mpileup args\fR] [\-\-bcftools \fIbcftools args\fR]
.
.SH "DESCRIPTION"
Parallel version of samtools mpileup in map\-reduce fashion\. Sambamba splits input BAM files into chunks and feeds them to samtools mpileup and, optionally, bcftools in parallel\. The chunks are slightly overlapping so that variant calling should not be impacted by these manipulations\. The obtained results from the multiple processes are combined as ordered output\. Named pipes are created in TMPDIR\.
.
.P
Sambamba mpileup relies on external tools and acts as a multi\-core implementation of samtools + bcftools\. Therefore, the following tools should be present in the PATH:
.
.IP "" 4
.
.nf

* samtools
* bcftools (when used)
.
.fi
.
.IP "" 0
.
.IP "\(bu" 4
If \-\-samtools is skipped, samtools mpileup is called with default arguments \'samtools\'
.
.IP "\(bu" 4
If \-\-bcftools is used without parameters, samtools is called with switch \'\-gu\' and bcftools is called as \'bcftools view \-Ov\'
.
.IP "\(bu" 4
If \-\-bcftools is skipped, bcftools is not called
.
.IP "" 0
.
.SH "OPTIONS"
.
.IP "\(bu" 4
\fB\-F\fR, \fB\-\-filter=FILTER\fR set custom filter for alignments
.
.IP "\(bu" 4
\fB\-L\fR, \fB\-\-regions=FILENAME\fR provide BED file with regions (no need to duplicate it in samtools args); all input files must be indexed
.
.IP "\(bu" 4
\fB\-o\fR, \fB\-\-output\-filename=<STDOUT>\fR specify output filename
.
.IP "\(bu" 4
\fB\-t\fR, \fB\-\-nthreads=NTHREADS\fR maximum number of threads to use
.
.IP "\(bu" 4
\fB\-b\fR, \fB\-\-buffer\-size=4_000_000\fR chunk size (in bytes)
.
.IP "" 0
.
.SH "BUGS"

