.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "SAMBAMBA" "1" "April 2013" "" ""
.
.SH "NAME"
\fBsambamba\fR \- toolkit for working with SAM/BAM files
.
.SH "SYNOPSIS"
\fBsambamba\fR [subcommand] [arguments\.\.\.]
.
.SH "DESCRIPTION"
\fBsambamba\fR unifies several independent tools in one executable:
.
.IP "\(bu" 4
sambamba\-view(1)
.
.IP "\(bu" 4
sambamba\-index(1)
.
.IP "\(bu" 4
sambamba\-merge(1)
.
.IP "\(bu" 4
sambamba\-sort(1)
.
.IP "\(bu" 4
sambamba\-flagstat(1)
.
.IP "\(bu" 4
sambamba\-slice(1)
.
.IP "" 0
.
.P
Thus available subcommands are \fIview\fR, \fIindex\fR, \fImerge\fR, \fIsort\fR, \fIflagstat\fR, and \fIslice\fR\. Their use is explained on the corresponding man pages\.
